### ISSUE TITLE
How to run demo?

### ISSUE THREAD

**Issue by melgard1** [clach04/python-tuya#44] opened 2018-11-10 04:52 UTC
New to python. Have installed python-tuya on Raspberry Pi using
`python -m pip install python-tuya`

I copied the demo code into demo.py and tried to run it.

```
python demo.py
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    d = pytuya.OutletDevice(deviceid, ipaddress, key)
AttributeError: 'module' object has no attribute 'OutletDevice'
```

**Comment by dmelgar** [comment] 2018-11-10 18:17
FYI: Was caused by running against python v2.7.13. I switched to using `python3`, version 3.5.3 and its working great!

**Comment by clach04** [comment] 2018-11-13 06:28
That's really odd, the Python version should have no impact on device class access. Closing, if more information surfaces we can review and figure out what's going on.

**Closed as completed by clach04** 2018-11-13 06:28 UTC

**Comment by dachshund-digital** [comment] 2019-06-27 19:05
Same issue with my attempt.  I installed using # pip3 install python-tuya.  No errors.  I am running python 3.5.3.  Tried to list classes via import, dir method, no classes shown.\

pip3 install python-tuya

python
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> import pytuya
 >>> dir(pytuya)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
